Expect bundled freetype on aix for JDK13 and up
adoptium/temurin-build pull request #2585
Opened 2021-04-19 17:01 UTC by adamfarley

The default behaviour for openjdk builds on AIX for JDK13+ is to bundle
freetype by default. So our freetype bundling test should be modified to 
expect this.

Signed-off-by: Adam Farley <adfarley@redhat.com>

2021-04-19 17:03 UTC, adamfarley commented
Test runs:

JDK16: https://ci.adoptopenjdk.net/job/Grinder/183/console
JDK8: https://ci.adoptopenjdk.net/job/Grinder/184/console

They both fail due to other tests falling down, but they pass "freetypeOnlyBundledOnCertainPlatforms".

2021-04-19 17:40 UTC, M-Davies requested changes
One linter issue
```
2021-04-19 17:03:33 [INFO]   File:[test/functional/buildAndPackage/src/net/adoptopenjdk/test/BundledFreetypeTest.java]
2021-04-19 17:03:34 [ERROR]   Found errors in [checkstyle] linter!
2021-04-19 17:03:34 [ERROR]   Error code: 1. Command output:
------
Starting audit...
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/BundledFreetypeTest.java:83:49: '13' is a magic number. [MagicNumber]
Audit done.
Checkstyle ends with 1 errors.
------
```

2021-04-19 17:49 UTC, adamfarley commented
I think we can safely ignore the magic number problem. There's currently an issue open to reduce the linter sensitivity: https://github.com/AdoptOpenJDK/openjdk-build/issues/2581

I've made sure this "magic number" issue is mentioned specifically. Linter, in the past, has objected to a great many numbers.

2021-04-19 19:25 UTC, sophia-guo approved these changes
LGTM

2021-04-19 19:32 UTC, M-Davies approved these changes

2021-04-20 08:50 UTC, adamfarley commented
@AdoptOpenJDK/tsc - Approval to merge during the lockdown cycle please

2021-06-08 08:28 UTC, merged

2021-06-08 09:04 UTC, adamfarley commented
Thanks Martijn :)