Switch codesigning to use Eclipse Foundation certificate
adoptium/temurin-build pull request #2619
Opened 2021-05-11 15:29 UTC by gdams

Currently this only works for Windows and macOS (jdk8u). I will need to fix up the remaining macOS versions.

2021-05-11 17:58 UTC, karianna requested changes

2021-05-11 17:58 UTC, karianna commented on sign.sh
> +        echo "$FILES" | while read -r f; do codesign --entitlements "$ENTITLEMENTS" --options runtime --timestamp --sign "Developer ID Application: London Jamocha Community CIC" "$f"; done
Swap LJC to Eclipse here?

2021-05-11 17:58 UTC, karianna commented on sign.sh
> +  BUILD_CONFIG[OS_KERNEL_NAME]="cygwin"
Is it always cygwin?  Why are we doing this?

2021-05-11 17:58 UTC, karianna commented on build-farm/platform-specific-configurations/mac.sh
> +  ## shellcheck disable=SC2006
Add a TODO here

2021-05-11 19:40 UTC, andrew-m-leonard approved these changes
lgtm

2021-05-12 09:09 UTC, karianna approved these changes
LGTM

2021-05-12 09:58 UTC, merged