Tactical fix to force OpenJ9 JDK17 to download a HotSpot boot JDK
adoptium/temurin-build pull request #2624
Opened 2021-05-12 11:34 UTC by sxa

Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2119 until https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2145 is resolved.

Signed-off-by: Stewart X Addison <sxa@redhat.com>

2021-05-12 11:42 UTC, M-Davies reviewed
Can we add a TODO comment to note that this is a temporary change?

2021-05-12 11:44 UTC, M-Davies requested changes
Also linter problems
```
2021-05-12 11:37:50 [ERROR]   Error code: 1. Command output:
------

In build-farm/platform-specific-configurations/linux.sh line 92:
  echo === START OF ARM32 STATUS CHECK
  ^-- SC2284: Use [ x = y ] to compare values (or quote '==' if literal).


In build-farm/platform-specific-configurations/linux.sh line 96:
  echo === END OF ARM32 STATUS CHECK
  ^-- SC2284: Use [ x = y ] to compare values (or quote '==' if literal).


In build-farm/platform-specific-configurations/linux.sh line 115:
      if [ "$BOOT_JDK_VERSION" -eq 16 ] && [ "VARIANT" = "openj9" ] && [ "ARCHITECTURE" = "aarch64" ]; then
                                                       ^-- SC2050: This expression is constant. Did you forget the $ on a variable?
                                                                                        ^-- SC2050: This expression is constant. Did you forget the $ on a variable?
```

2021-05-12 14:27 UTC, sxa commented
Added TODO ... Although all of the whole of the auto-download stuff was only supposed to be temporary ;-)

2021-05-12 14:34 UTC, sxa commented
Side note: this definitely counts as one of the most pointless messages I've seen from a linter;
```
  echo === START OF ARM32 STATUS CHECK
  ^-- SC2284: Use [ x = y ] to compare values (or quote '==' if literal).
```

2021-05-12 14:42 UTC, M-Davies approved these changes

2021-05-12 16:00 UTC, sxa commented
Build failure is not related to this PR as it's been seen elsewhere.

2021-05-13 18:37 UTC, andrew-m-leonard approved these changes

2021-05-14 10:10 UTC, sxa commented
https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/ARCHITECTURE=aarch64,OS=ubuntu18,label=qemu/261/consoleFull seems to have done the right thing, so merging

2021-05-14 10:10 UTC, merged