switch bootJDK download scripts to use adoptium binaries
adoptium/temurin-build pull request #2711
Opened 2021-09-13 08:40 UTC by gdams

fixes: https://github.com/adoptium/temurin-build/issues/2704

2021-09-13 08:42 UTC, jerboaa approved these changes
Looks fine to me.

2021-09-13 08:47 UTC, karianna requested changes
Should we be using GH setup-java action for this?  Am also worried that adoptium only pulls down subset of adoptopenjdk API

2021-09-13 08:47 UTC, karianna commented on .azure-devops/build/steps/macOS/before.yml
> +          wget -O "${{ parameters.dependenciesDir }}/openjdk.tar.gz" "https://api.adoptium.net/v3/binary/latest/${BOOTJDK_VERSION}/ea/mac/x64/jdk/hotspot/normal/adoptium?project=jdk"
I don't think adoptium can sever up 15 binaries no?

2021-09-13 08:59 UTC, gdams commented
> Should we be using GH setup-java action for this? Am also worried that adoptium only pulls down subset of adoptopenjdk API

No one of the main reasons we don't is because we want to test the code that pulls down boot JDK's. I've added another check which will fall back to adoptopenjdk if required.

2021-09-13 10:31 UTC, gdams commented
Test failures are unrelated to this change

2021-09-13 10:42 UTC, karianna approved these changes

2021-09-13 10:44 UTC, karianna commented
I'm going to merge this as it'll help with testing any emergency PRs WRT to java 17

2021-09-13 10:44 UTC, merged

2021-09-13 18:18 UTC, sxa commented
@karianna @gdams I can see the fallback to adoptopenjdk in the linux script here but not the others. Isn't this introducing a bit of a risk? Given that we have the forwarding from adoptopenjdk->adoptium I'm not clear on why we're pushing this through during a lockdown period.

2021-09-14 15:27 UTC, karianna commented
> @karianna @gdams I can see the fallback to adoptopenjdk in the linux script here but not the others. Isn't this introducing a bit of a risk? Given that we have the forwarding from adoptopenjdk->adoptium I'm not clear on why we're pushing this through during a lockdown period.

17/tip builds were failing for GH Actions which meant we didn't have PR testing on any changes we might need to push through during release week, so this was worth getting in (it certainly couldn't make it worse).