Sign AIX and Linux release
adoptium/temurin-build pull request #2720
Opened 2021-09-22 13:18 UTC by vsebe

Sign tarballs, executables and shared library for AIX and Linux
platforms.
Remove hardcoded certificate name for code signing.

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

2021-09-23 11:28 UTC, karianna requested changes

2021-09-23 11:28 UTC, karianna commented on sign.sh
> +        echo "Unknow $SIGN_TOOL, skipping code signing on $OPERATING_SYSTEM"
typo in unknow

2021-09-23 13:32 UTC, vsebe commented on sign.sh
> +        echo "Unknow $SIGN_TOOL, skipping code signing on $OPERATING_SYSTEM"
fixed

2021-10-06 19:20 UTC, AdamBrousseau approved these changes

2021-11-22 18:35 UTC, AdamBrousseau commented
Can we move forward on this? I think Adopt is looking into signing linux and aix. I wouldn't want that effort duplicated.

2023-11-14 11:45 UTC, sxa commented
This seems to have got a bit lost - is this change still required? 
@AdamBrousseau @andrew-m-leonard

2023-11-15 13:44 UTC, andrew-m-leonard commented
i'm not aware of this...

2024-01-08 23:42 UTC, closed without merging

2024-01-08 23:42 UTC, smlambert commented
@AdamBrousseau - I am going to close this PR, with the idea that if it is still needed a fresh one will get created or it can be re-opened.