update releasing nodes to include linux installers, homebrew and docker
adoptium/temurin-build pull request #2822
Opened 2022-01-11 11:22 UTC by gdams

2022-01-11 11:25 UTC, karianna approved these changes
LGTM

2022-01-11 12:52 UTC, sxa requested changes
As per slack conversations can we also add some information on the use of the [aarch32 mirror job](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/git-hg-aarch32-jdk8u/) particularly in terms of the correct parameters that need to be used before running the build. Also are there any notes / protection we can put in place regarding [this failure](https://github.com/adoptium/mirror-scripts/issues/12)?

Also to close off https://github.com/adoptium/temurin-build/issues/2168 we should probably add a step "Make sure the GA tags have been mirrored to our repository and if not manually run <blah>"

2022-01-11 12:52 UTC, sxa commented on RELEASING.md
> +1. [Mac only] Once the binaries are available on the website you need to update the Homebrew casks. There are 3 casks in total ([`temurin`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks
Clarify whether it needs to be three separate PRs against the three casks.
Also possibly provide a link to a JDK8 one alongside the JDK17 one as it's a "simpler" case without the change of `U` (which is also good as an example here of course!)

2022-01-11 12:52 UTC, sxa commented on RELEASING.md
> +1. [Mac only] Once the binaries are available on the website you need to update the Homebrew casks. There are 3 casks in total ([`temurin`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks
Perhaps add a note that saying that you can easily copy the the SHAs for inclusion in the PR from the temurin download website for [8](https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot), [11](https://adoptium.net/releases.html?variant=openjdk11&jvmVariant=hotspot) and [17](https://adoptium.net/releases.html?variant=openjdk17&jvmVariant=hotspot)

2022-01-11 12:52 UTC, sxa commented on RELEASING.md
> +1. [Docker] please see https://github.com/adoptium/containers#maintenance-of-dockerfiles
I think the formatting will need some fixup here as the two previous bullet points have caused this to show as step 1 again.

2022-01-11 12:52 UTC, sxa commented on RELEASING.md
> +1. [Linux only] Once the binaries are available on the website you can begin updating the specfiles for the RPM/DEB files. There are 3 different type of linux installer ([debian](https://github.com/a
Presumably it is valid to run the packages job without `UPLOAD` initially to use as a `dry-run` similar to the main publish job to verify that no errors occur? Perhaps worth explicitly making that suggestion.

2022-01-11 12:55 UTC, gdams commented
> As per slack conversations can we also add some information on the use of the aarch32 mirror job particularly in terms of the correct parameters that need to be used before running the build. Also are there any notes / protection we can put in place regarding this failure?

@sxa that was added some time ago:

See the section in the README:
     - For HotSpot (arm32), the tag usually takes the form `jdk8u322-b04-aarch32-xxxxxxxx`
     - NOTE you need to set `overridePublishName` for arm32 to the actual OpenJDK tag (`jdk8u322-b04`)

2022-01-15 14:32 UTC, sxa commented
>  @karianna requested a review from sxa yesterday 

Other than the replies about the need for the aarch32 mirror docs, my origin review comments still stand.

2022-02-07 11:10 UTC, sxa commented
Also needs info about the changelog updates being required as that tripped me up when attempting the updates in this cycle.

2022-02-17 14:04 UTC, sxa requested changes
A couple of remaining clarity / typo fixes required.

2022-02-17 14:04 UTC, sxa commented on RELEASING.md
> +1. [Linux only] Once the binaries are available on the website you can begin updating the specfiles for the RPM/DEB files. There are 3 different type of linux installer ([debian](https://github.com/a
Ref my initial comment:

> Presumably it is valid to run the packages job without UPLOAD initially to use as a dry-run similar to the main publish job to verify that no errors occur?

I don't think the job currently has a parameter called `dry-run` (but we should possibly change the job to do so) so this needs to say "It is suggested that you run the job with `UPLOAD` unchecked first"

2022-02-17 14:04 UTC, sxa commented on RELEASING.md
> +1. [Mac only] Once the binaries are available on the website you need to update the Homebrew casks. There are 3 casks in total ([`temurin`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks
```suggestion
1. [Mac only] Once the binaries are available on the website you need to update the Homebrew casks. There are 3 casks in total ([`temurin`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/temurin.rb) which always serves the latest version, [`temurin8`](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/temurin8.rb) and [`temurin11`](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/temurin11.rb)). An example PR can be found [here](https://github.com/Homebrew/homebrew-cask/commit/4565865e9d7c3d3018ee8aa67803ea68c54dde86). SHA sums can be easily copied from the website. The separate pull request is required for each version you update. If in doubt reach out to George (gdams) as he's a maintainer.
```

2022-04-22 09:39 UTC, sxa commented
@gdams Is there anything blocking a response on the suggestions above?

2022-05-09 14:15 UTC, closed without merging