Remove get_source_dragonwell.sh, Dragonwell8 is monorepo
adoptium/temurin-build pull request #2912
Opened 2022-05-05 03:13 UTC by joeyleeeeeee97

Dragonwell 8 is a monorepo now, and get_source is removed.

2022-05-05 10:13 UTC, karianna commented
@joeyleeeeeee97 - the build failed on jdk8u.

2022-05-09 09:50 UTC, joeyleeeeeee97 commented
@karianna Fixed. Dragonwell8 requires a bootstrap image, please take a look

2022-05-09 10:21 UTC, karianna approved these changes
LGTM

2022-05-10 11:41 UTC, sxa requested changes
I'm not sure this is the best place to set that boot JDK.
@karianna Can we look at getting https://github.com/adoptium/temurin-build/pull/2828 merged instead so this PR doesn't have to have the Dragonwell-specific download in it?

2022-05-10 11:48 UTC, karianna commented
Asked for another review on that PR

2022-05-13 11:14 UTC, sxa commented
@joeyleeeeeee97 Now that the other PR has been merged, can we remove the github workflow changes from this PR relating to the boot JDK?

2022-05-13 11:32 UTC, joeyleeeeeee97 commented
@sxa Yes! Thanks.
Updated this PR, waiting for github action results.

2022-05-13 12:09 UTC, sxa commented
@joeyleeeeeee97 Thanks!
I've just noticed that the current build doesn't seem to  work with dragonwell 8.0.0 as the boot JDK which is the one listed in https://github.com/adoptium/temurin-build/blob/92ff4b166ec4dc38a73c121e798a18794f129fd4/build-farm/platform-specific-configurations/linux.sh#L123 - can you update that with a more suitable one (Can't remember which version you had before the latest change, but it seems to work ok with 8.11.12)

2022-05-13 12:35 UTC, joeyleeeeeee97 commented
@sxa , Yes. updated with 8.11.12.

2022-05-13 15:10 UTC, sxa approved these changes
Merging build changes on a Friday afternoon is usually a really bad idea, but I'm going to do it anyway ;-)

2022-05-13 15:10 UTC, merged