Amend OS/Kernel version reporting to include pretty o/s and kernel version.
adoptium/temurin-build pull request #3032
Opened 2022-07-08 09:52 UTC by steelhead31

Fixes #3010

2022-07-08 12:37 UTC, karianna requested changes
Whitespace seems incorrect?

2022-07-11 10:11 UTC, karianna requested changes
suggested some more whitespace fixes

2022-07-11 10:11 UTC, karianna commented on sbin/common/config_init.sh
> +# The OS kernel name, e.g. 'darwin' for Mac OS X
```suggestion
  # The OS kernel name, e.g. 'darwin' for Mac OS X
```

2022-07-11 10:11 UTC, karianna commented on sbin/common/config_init.sh
> +BUILD_CONFIG[OS_KERNEL_NAME]=$(uname | awk '{print tolower($0)}')
```suggestion
  BUILD_CONFIG[OS_KERNEL_NAME]=$(uname | awk '{print tolower($0)}')
```

2022-07-11 15:42 UTC, zdtsw approved these changes
LGTM

2022-07-11 15:45 UTC, merged