Add --build-reproducible-date=ISO8601_date build option to allow reroducible nightly builds
adoptium/temurin-build pull request #3166
Opened 2022-11-25 20:18 UTC by andrew-m-leonard

Add --build-reproducible-date=ISO8601_date build build arg, which sets the build date & time used in the build
so for nightly builds the pre/post version output date, and all build dates are reproducible.

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

2022-11-26 04:51 UTC, karianna approved these changes
LGTM

2022-11-26 04:53 UTC, karianna requested changes
Looks like GH Actions for the Alpine build couldn't take the new setting

2022-11-26 15:28 UTC, andrew-m-leonard commented
> Looks like GH Actions for the Alpine build couldn't take the new setting

@karianna thanks, I was using the wrong empty string test !

2022-11-26 20:24 UTC, tellison approved these changes

2022-11-27 08:38 UTC, karianna approved these changes

2022-11-27 08:38 UTC, merged

2022-11-27 09:50 UTC, zdtsw commented
bit late, but try to understand this PR:
In Jenkins,  we need to pass a new field `BUILD_REPRODUCIBLE_DATE` from jenkins job, which set the correct 'date'
The build result binary should be able to be comparison(as long as 2 builds have same `BUILD_REPRODUCIBLE_DATE` value, even the `releaseType` is "`Nightly`" if  it is `jdk17+` ?

2022-11-27 11:38 UTC, andrew-m-leonard commented
> bit late, but try to understand this PR: In Jenkins, we need to pass a new field `BUILD_REPRODUCIBLE_DATE` from jenkins job, which set the correct 'date' The build result binary should be able to be comparison(as long as 2 builds have same `BUILD_REPRODUCIBLE_DATE` value, even the `releaseType` is "`Nightly`" if it is `jdk17+` ?

Yes, the next PR logic to use this option will use it for jdk17, and jdk19+