github: only run build if it is scripts changes
adoptium/temurin-build pull request #3176
Opened 2022-12-08 11:50 UTC by zdtsw

- no need run it if it is .md files

2022-12-10 14:04 UTC, gdams requested changes
1 change please and then this should be good to go

2022-12-10 14:04 UTC, gdams commented on .github/workflows/build.yml
> +      - "**.sh"
You should also include this specific workflow file (so we can test changes made to it)

Should just be able to add .github/workflows/build.yml as a path.

2022-12-11 19:31 UTC, gdams approved these changes

2022-12-12 08:14 UTC, karianna approved these changes
LGTM

2022-12-12 08:14 UTC, merged