Created a sign-sbom script to build cyclonedx library and sign the sbom
adoptium/temurin-build pull request #3215
Opened 2023-01-12 09:18 UTC by julian55455

Created a sign-sbom script to build cyclonedx library and sign the sbom

2023-01-13 19:12 UTC, karianna commented
@julian55455 Linter fails.

2023-01-25 15:54 UTC, andrew-m-leonard commented
@julian55455 This will be the jenkins called script, use https://github.com/adoptium/temurin-build/blob/master/build-farm/sign-releases.sh
as an example. so it will be called with the sbom JSON artifact to be signed copied from the upstream job to a folder called workspace/target/...json

eg:
```
workspace/target/OpenJDK17U-sbom_arm_linux_hotspot_17.0.6_10.json
```

You sign it, and then the Jenkins job itself will archive the signed artifact.

2023-01-25 15:55 UTC, andrew-m-leonard requested changes

2023-01-25 15:55 UTC, andrew-m-leonard commented on build-farm/sign-sbom.sh
> +#!/bin/bash
Use this example as the basis of what this script needs to do: https://github.com/adoptium/temurin-build/blob/master/build-farm/sign-releases.sh

2023-01-25 15:55 UTC, zdtsw commented
this script wont do any harm, as long as it is not get called.
but good to have #3211 fixed first then correct the script and add a caller

2023-03-03 13:54 UTC, closed without merging