alpine: switch jdk8u to build from other fork
adoptium/temurin-build pull request #3217
Opened 2023-01-13 20:49 UTC by gdams

As per https://github.com/adoptium/jdk8u/issues/11, we are splitting the JDK8u Alpine specific patches into their own separate mirror to keep our mainline jdk8u repo as clean as possible.

2023-01-13 21:04 UTC, karianna approved these changes
LGTM

2023-01-13 21:27 UTC, karianna requested changes
Linter failure:
In /github/workspace/configureBuild.sh line 180:
  elif [ "${BUILD_CONFIG[OPENJDK_CORE_VERSION]}" == "${JDK8_CORE_VERSION}" ] && [ "${BUILD_CONFIG[OS_FULL_VERSION]}" == *"Alpine"* ] && [[ "${BUILD_CONFIG[BUILD_VARIANT]}" == "${BUILD_VARIANT_TEMURIN}" ]]; then
                                                                                                                        ^--------^ SC20[81](https://github.com/adoptium/temurin-build/actions/runs/3914819884/jobs/6692303752#step:4:82) (error): [ .. ] can't match globs. Use [[ .. ]] or case statement.

2023-01-14 12:11 UTC, gdams commented
@karianna updated PTAL

2023-01-14 22:56 UTC, karianna approved these changes

2023-01-15 16:21 UTC, andrew-m-leonard approved these changes

2023-01-15 20:47 UTC, merged