Enable build scripts support for any user variant
adoptium/temurin-build pull request #3344
Opened 2023-05-15 09:32 UTC by andrew-m-leonard

Fixes https://github.com/adoptium/temurin-build/issues/3343

Change the ERROR exit policing of the vendor name, to just a WARNING.
And allow setting the vendor-url, vendor-bug-url, vendor-vm-bug-url.

2023-05-15 10:45 UTC, karianna approved these changes

2023-05-15 12:19 UTC, sxa requested changes
Also https://github.com/adoptium/temurin-build/blob/master/makejdk-any-platform.1 should be updated to document the new parameters.

2023-05-16 09:18 UTC, andrew-m-leonard commented
> Is there any reason why someone using their own value (through customer configure args) wouldn't be using a VARIANT of `hotspot`?
> 
> I'm curious as to what use case would cause this to be a problem, and by removing this check we're not going to be trapping typos on the valid VARIANT values.

@sxa Hmm, you make an interesting point, I need to go back and try this again, as the problems I was seeing related to vendor vs variant interchange in our scripts...

2023-05-16 15:08 UTC, andrew-m-leonard commented
Yep @sxa , my misstake I had accidently changed VARIANT in my env script. It's just the vendor- build args that are added now, for review please...

2023-05-16 17:25 UTC, sxa approved these changes

2023-05-17 01:53 UTC, merged