doc: Add EclipseMirror information to RELEASING.md
adoptium/temurin-build pull request #3365
Opened 2023-05-24 11:25 UTC by sxa

We have a mirror of the github artifacts on an Eclipse-owned server. This is a manual step once all fo the artefacts are in GitHub.

Note that because of how the credentials for pushing to the Eclipse repository are managed, this step has to be done on the Temurin Compliance jenkins instance.

2023-05-25 04:05 UTC, karianna approved these changes

2024-01-31 12:29 UTC, Haroon-Khel approved these changes

2024-01-31 12:31 UTC, Haroon-Khel requested changes
https://github.com/adoptium/temurin-build/issues/3355#issuecomment-1560927672 points to an issue comment, should it not point to https://ci.eclipse.org/temurin-compliance/job/EclipseMirror/?

2024-01-31 12:47 UTC, Haroon-Khel approved these changes

2024-01-31 12:47 UTC, sxa commented
> [#3355 (comment)](https://github.com/adoptium/temurin-build/issues/3355#issuecomment-1560927672) points to an issue comment, should it not point to https://ci.eclipse.org/temurin-compliance/job/EclipseMirror/?

I think it was supposed to reference the issue where we did the EclipseMirror implementation. I generall prefer not to have direct links in the TC instance, but given that it's a big usability boost, I've done that and removed the line in the "publicising" section below which duplicates the information about the release mirror job.

2024-01-31 20:05 UTC, merged