Enable GCC 10 for RISC-V
adoptium/temurin-build pull request #3590
Opened 2023-12-20 13:00 UTC by luhenry

Given the rapid evolution of RISC-V, the newer the GCC toolchain, the better.

2023-12-20 13:12 UTC, sxa requested changes

2023-12-20 13:12 UTC, sxa commented on build-farm/platform-specific-configurations/linux.sh
> +if [ "${ARCHITECTURE}" == "ricv64" ] && [ "${VARIANT}" == "${BUILD_VARIANT_HOTSPOT}" ] && [ -r /usr/bin/gcc-10 ]; then
Typo in `riscv64` and it should be an `elif` statement. I'm also suggesting removing the variant check as our normal builds are with a `VARIANT` of `temurin` distinct from `hotpot` and the only potential exception of dragonwell is covered in the previous clause. Perhaps we should check for either of those two but given that gcc-9 seemed generally quite broken in earlier tests I'm inclined to just stick with this.
```suggestion
elif [ "${ARCHITECTURE}" == "riscv64" ] && [ -r /usr/bin/gcc-10 ]; then
```

2023-12-21 15:18 UTC, sxa approved these changes

2023-12-21 15:19 UTC, tellison approved these changes

2023-12-21 15:40 UTC, merged