Update GNUPGHOME variable more broadly
adoptium/temurin-build pull request #3630
Opened 2024-02-03 15:23 UTC by luhenry

It's an issue on linux-riscv64 valuation pipelines for jdk23. See https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk23/job/jdk23-evaluation-linux-riscv64-temurin/2/console for example.

2024-02-03 15:31 UTC, gdams approved these changes

2024-02-03 21:29 UTC, luhenry commented
I can confirm this latest version works as seen on https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk22/job/jdk22-evaluation-linux-riscv64-temurin/18/console

2024-02-03 21:32 UTC, luhenry commented
I can confirm this work, see https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk22/job/jdk22-evaluation-linux-riscv64-temurin/19/console for details.

2024-02-04 17:51 UTC, sxa approved these changes

2024-02-04 18:06 UTC, sxa requested changes
PR checks have failed so I'm going to put a block on this, but as an FYI JDK22 (required as a boot JDK for 23) has now been published at

2024-02-05 09:56 UTC, luhenry commented
The PR checks have failed either on "No space left of device" or "No such file or directory" for files which are not in `/tmp`. The failures then seem unrelated to this change.

2024-02-05 13:27 UTC, sxa commented
The build failures (I'm ignoring the smoke test one for now which is three or of space one) seem related to the gpg key. I didn't think we had any issues with that at the moment. @andrew-m-leonard can you cast an eye over this and see if this failure is expected at the moment?

2024-02-06 09:04 UTC, andrew-m-leonard approved these changes
lgtm lets give it a try

2024-02-06 11:48 UTC, merged

2024-02-06 11:50 UTC, sxa commented
Re-running your original failing job at https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk23/job/jdk23-evaluation-linux-riscv64-temurin/12/console now that this PR has been merged.

2024-02-06 12:16 UTC, sxa commented
I'm a little unclear on how we've ended up with a `jdk23` folder at:
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk23/
which is distinct from `jdk` at:
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk/
But it's failing trying to clone https://github.com/adoptium/jdk23.git I've kicked off the above test again using the `jdk` one at https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk/job/jdk-evaluation-linux-riscv64-temurin/63/console and it's looking happier so we'll see how far it gets.