IVT: Trap case where limited platforms mean no zip or no tgz exist in release
adoptium/temurin-build pull request #3798
Opened 2024-05-07 18:11 UTC by sxa

Fixes https://github.com/adoptium/temurin/issues/28#issuecomment-2085303993

Recommend reviewing ignoring whitespace as this is a simple change but adds indents due to the if section.

2024-05-08 02:31 UTC, karianna approved these changes

2024-05-08 16:23 UTC, sxa commented
Also fixes https://github.com/adoptium/temurin-build/issues/3801

I would normally have done this in a separate PR but I needed to test it all together to do it properly and this has only had one approval so far, therefore requesting @karianna to re-approve.

2024-05-08 23:01 UTC, karianna approved these changes

2024-05-08 23:01 UTC, karianna commented
In /github/workspace/tooling/release_download_test.sh line 214:
  for A in `ls -1d OpenJDK*.tar.gz OpenJDK*.zip *.msi *.pkg *sbom*[0-9].json`; do
           ^-- SC2045 (warning): Iterating over ls output is fragile. Use globs.
           ^-- SC2006 (style): Use $(...) notation instead of legacy backticks `...`.
                                                ^-- SC2035 (info): Use ./*glob* or -- *glob* so names with dashes won't become options.
                                                      ^-- SC2035 (info): Use ./*glob* or -- *glob* so names with dashes won't become options.
                                                            ^-- SC2035 (info): Use ./*glob* or -- *glob* so names with dashes won't become options.

2024-05-08 23:01 UTC, karianna requested changes
linter fixes needed

2024-05-13 21:26 UTC, karianna approved these changes

2024-05-17 08:24 UTC, andrew-m-leonard approved these changes

2024-05-18 05:28 UTC, merged