Added top-level comaprator script
adoptium/temurin-build pull request #3991
Opened 2024-10-11 12:06 UTC by judovana

2024-10-11 12:10 UTC, judovana commented
I iwll add license header and do the linter exercise once we agree it is desirbale work to go in. TY!

2024-10-14 08:38 UTC, judovana commented on tooling/compare-builds.sh
> +    echo "dead" > "${WORKDIR}/${JDK_INFO["first_name"]}/bin/java"
The `${DO_BREAK:-}"` block  is serving to tempt your toolchain a bit. In the moment  I saw it claims some buiilds to be reproducible., I wanted to modify some parts to see if results are as they should be.  At the end I left only this two simple modification as placeholder where to do something like that  - or use  as it is.  I do not have hard feelings to remove it, but it was useful.

2024-10-14 09:48 UTC, karianna commented
linter is upset :-)

2024-10-14 10:28 UTC, judovana commented
> linter is upset :-)

Linter is never upset, it just gently reminds!

2024-10-15 10:54 UTC, andrew-m-leonard requested changes
I'm not sure at the moment we want to add this as another top-level script, which may just complicate things...

2024-10-15 11:03 UTC, judovana commented
Sure. I have no objections to  not  include this one. But word "another" is interesting.  I have not noticed anythig similar around. . I  definitely do not want myself, nor anybody else to  to keep "supporting" two top level wrappers,  but would like to have one which do its job properly.   So I would like to adjust the already existing to do what I need,  or move workloads which are using the current one to this new one.  Can you please pin point me?

2024-10-15 14:35 UTC, andrew-m-leonard commented
> Sure. I have no objections to not include this one. But word "another" is interesting. I have not noticed anythig similar around. . I definitely do not want myself, nor anybody else to to keep "supporting" two top level wrappers, but would like to have one which do its job properly. So I would like to adjust the already existing to do what I need, or move workloads which are using the current one to this new one. Can you please pin point me?

So "another" is actually relative to the "top level use case". We already have in this repo the new AQA rebuild tests here for example: https://github.com/adoptium/temurin-build/blob/5035fa3b6bfc1787c94d7b1e91e2979619b9e02a/test/system/reproducibleCompare/playlist.xml#L22

2024-10-15 14:43 UTC, smlambert commented
I will close this PR as unnecessary/duplicate, especially as we prefer to use our existing approach and leverage existing AQAvit tools such as TRSS when running and monitoring comparisons and reproducible tests. 

Also as a reminder, PRs should be related to existing issues which are either in backlog or accepted into a quarterly plan by component owners / PMC / project leads, so we can ensure that we are prioritizing our time and resources well.

2024-10-15 14:43 UTC, closed without merging

2024-10-15 15:12 UTC, judovana commented
> > Sure. I have no objections to not include this one. But word "another" is interesting. I have not noticed anythig similar around. . I definitely do not want myself, nor anybody else to to keep "supporting" two top level wrappers, but would like to have one which do its job properly. So I would like to adjust the already existing to do what I need, or move workloads which are using the current one to this new one. Can you please pin point me?
> 
> So "another" is actually relative to the "top level use case". We already have in this repo the new AQA rebuild tests here for example:
> 
> https://github.com/adoptium/temurin-build/blob/5035fa3b6bfc1787c94d7b1e91e2979619b9e02a/test/system/reproducibleCompare/playlist.xml#L22

Yah, I have seen that playlist. It did not seems to be doing what I wanted.  I will try to look again.

> AQAvit tools such as TRSS when running and monitoring comparisons and reproducible tests.

Sure, but there is absiolutely no reason an testsuite could generate  more types of results.

2024-10-15 15:36 UTC, judovana commented
@smlambert  Actually one more thing.  Three weeks ago I wanted to run compare of one jdk against existing temurins. There was (and afaik still is)  nothing which is helping to glue all the parts together to compare existing build against  released temurins.  Especially under cygwin.  
So I wrote it, and it was well standalone  be well reusable,  tested in cygwin and fedora/rhel.  So I have naturally offered it back to the project from which  the individual parts, and a pretty long readme (which do not mention any top level wrapper) come from (I have searched for that, and found the playlists, and they do not supply what I needed).  So I'm wondering, why it is so hard  for you to be at least semi-welcoming, and  jsut  write. "sorry this is duplicated with already existing toolchain". And even better, to enhance readme how to use that if it is alrerady existing.   Also I'm wondering why one needs a PMC/governing board/whatever agreement, to contribute already existing, simple script.  Which dont take any time of your people.  Except review which would not be that hard considering it is jsut top level glue only. And if so, then it can always go on hold.