Enhance SBOM and JDK file check
adoptium/temurin-build pull request #4078
Opened 2024-12-04 21:38 UTC by sophia-guo

If no SBOM and JDK file available fail the job.

Related https://github.com/adoptium/aqa-tests/issues/5794

2024-12-04 21:39 UTC, sophia-guo commented
https://ci.adoptium.net/job/Test_openjdk21_hs_special.system_x86-64_windows/26/console

2024-12-05 03:44 UTC, smlambert approved these changes
LGTM

One question, did you intend to lose the indentation within the ifndef blocks of the .mk file?

2024-12-05 06:24 UTC, karianna requested changes

2024-12-05 06:24 UTC, karianna commented on test/system/reproducibleCompare/reproducible.mk
> +$(error ERROR! NO SBOM_FILE AVAILABLE)
whitespace probably needs fixing

2024-12-05 09:47 UTC, andrew-m-leonard approved these changes

2024-12-05 11:26 UTC, sxa requested changes
> https://ci.adoptium.net/job/Test_openjdk21_hs_special.system_x86-64_windows/26/console

I was expecting that link to be a re-run with the fix that showed the fix, but that is my original failing job link :-)

I guess it's not easy to run a re-test with an updated openjdk-build repo, so we can integrate this and then I can run the test against it again

Since it's been flagged by the other two above, I think it's worth fixing the whitespace issues (Blocking for now in case someone else merges this before you see the comments)

2024-12-05 14:27 UTC, sophia-guo commented
https://ci.adoptium.net/job/Test_openjdk21_hs_special.system_x86-64_windows/26/console is using my personal branch. @sxa

2024-12-05 14:52 UTC, sophia-guo commented
https://ci.adoptium.net/view/Test_grinder/job/Grinder/11936/console

This failure in makefile will fail the job and hence no other tests in same level will run and no test output will be archived. Currently no other tests in special.system, but it's not a good solution. Change it to draft.

2024-12-05 15:57 UTC, sophia-guo commented
Updated. Print ERROR message and usage infor. 
https://ci.adoptium.net/job/Grinder/11939/ - fail the test itself with ERROR message.
https://ci.adoptium.net/job/Grinder/11943/ - manually abort after the test start running.

2024-12-06 17:57 UTC, sxa approved these changes
> Updated. Print ERROR message and usage infor. https://ci.adoptium.net/job/Grinder/11939/

Just a minor point - it might be nicer if the error was inside the `Running test` block, but otherwise this LGTM and I'm fine with it going in like this!
```
15:12:19  ERROR! NO SBOM_FILE AVAILABLE
15:12:19  
15:12:19  ===============================================
15:12:19  Running test Rebuild_Same_JDK_Reproducibility_Test_win_0 ...
15:12:19  ===============================================
```

2024-12-06 19:58 UTC, sophia-guo commented
Inside the running test: it shows the usage of windows_repro_build_compare.sh information, which means parameters are missing. `ERROR! NO SBOM_FILE AVAILABLE` could help which parameter is missing.


```
10:12:20  Usage: C:/jenkins/workspace/Grinder/aqa-tests/\system\reproducibleCompare\windows_repro_build_compare.sh SBOM_URL/SBOM_PATH JDKZIP_URL/JDKZIP_PATH
10:12:20  
10:12:20  1. SBOM_URL/SBOM_PATH - should be the FULL path OR a URL to a Temurin JDK SBOM JSON file in CycloneDX Format
10:12:20      eg. https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-sbom_x64_windows_hotspot_21.0.2_13.json
10:12:20  
10:12:20  2. JDKZIP_URL/JDKZIP_PATH - should be the FULL path OR a URL to a Temurin Windows JDK Zip file
10:12:20      eg. https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_x64_windows_hotspot_21.0.2_13.zip
10:12:20  
10:12:20  3. REPORT_DIR - should be the FULL path OR a URL to the output directory for the comparison report
1
```

2024-12-08 00:22 UTC, karianna approved these changes

2024-12-08 00:22 UTC, merged